runtime: go112

env_variables:
  USING_APPENGINE: '1'

includes:
  - gracenote.yaml

handlers:
- url: /
  static_files: web/index.html
  upload: web/index.html

- url: /css
  static_dir: web/css

- url: /cddb(/.*)?
  script: _go_app